### ISSUE TITLE
[sim] [or] still integration problem for  SLICE D

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#342]
Hi @tomjorquera and @semmeneg 
testing and debugging your code for SLICE D i found some problems that still prevent me to test the scenario. In particular, i am guessing about 2 major concerns (but i may be wrong, as usual)
 1. dependency problem in the POM of the OR
 1. potential integration issue code between OR and SIM 

About 1, I discovered that OR has a dependency issue with "com.wcohen.secondstring". I did not fixed the pom yet with a PR, because maybe this dependency should be included into "cbr-core". @semmeneg could you please verify that.

About 2, even if and then processing the data sent from the SIM to the OR a strange error is spotted which brings to a "java.lang.UnsupportedOperationException". Apparentely the error cames only when the SIM sends data the OR, in fact (with the modification at point 1) the unit tests of the OR pass. I dug into it, and I understood (please @tomjorquera double check) that this is due to a java.util.Collections$UnmodifiableRandomAccessList that should be caused by an attempt form the OR to recover something that was declared as "unmodifiable". Looking for that string in the SIM code I discovered that actually the BPMNExplorer.java declares "unmodifiableMap". If this is the case either the SIM has to change the way it defines such maps, either the OR should relies on a more flexible approach which does not bring to the exception.

Please let me know.

FYI : @woshilapin, @acalabro

**Comment by gulyx** [comment]
I forgot to mention that the error in 2 is spotted by this line :   https://github.com/LearnPAd/learnpad/blob/master/lp-ontology-recommender/src/main/java/eu/learnpad/ontology/recommender/cbr/CBRAdapter.java#L215

**Comment by tomjorquera** [comment]
@gulyx, @semmeneg I do not think the error comes from the BPMNExplorer (otherwise something **very, very** wrong is going on). The data fromr the BPMN Explorer is not shared directly, and all data shared by the SIM to the OR pass by at least one (and for what I have seen more) marshalling-unmarshalling step.
I cannot verify by myself without deploying the whole platform, but I believe this problem probably comes more from one of the deserialization steps that maybe create an immutable collection.

In any case, I believe a very simple step would be to not try to directly manipulate the collection passed by the REST API, but to create a new collection containing the same elements:

If I understand the code correctly, replacing the line https://github.com/LearnPAd/learnpad/blob/master/lp-ontology-recommender/src/main/java/eu/learnpad/ontology/recommender/cbr/CBRAdapter.java#L105
with the following code:
`addProperties(simulationCase, key, new ArrayList((Collection)value));`
should be sufficient solve the issue, but maybe @semmeneg should confirm that.

**Comment by gulyx** [comment]
@tomjorquera thanks for the answer. In fact i was wrong ... as usual :D 
In parallel to you I came to a similar conclusion too. In fact in my code I tried to update all the instances 
` Arrays.asList`
with something like : 
`List list = new LinkedList(Arrays.asList(value));`
according to :
http://stackoverflow.com/questions/2965747/why-i-get-unsupportedoperationexception-when-trying-to-remove-from-the-list

the result is working, so @semmeneg, I will propose a PR on that. 

I would suggest to close this issue as soon as the PR is accepted AND after feedback form @semmeneg about 1.

**Comment by tomjorquera** [comment]
Right I forgot about this specificity of Arrays.asList! Good find.

**Comment by semmeneg** [comment]
Hi

fully agree. Arrays.asList() returns an immutable list. But since I do 
not manipulate that list and the JUnit test runs without errors I cannot 
see why this happens when running the whole application. But 
nevertheless, many thanks to the help and the solution found.

Please Guglielmo, I'm fine with the PR.
For the first issue with the secondstring repository not available 
anymore, I did just upload the adapted CBR-Core library.

Many thanks and best wishes
Sandro

**Comment by gulyx** [comment]
@semmeneg 

> For the first issue with the secondstring repository not available anymore, I did just upload the adapted CBR-Core library.

this mean i can remove the modification i did on my local OR pom, right?

**Comment by semmeneg** [comment]
Yes, you can.

**Comment by gulyx** [comment]
... i still have errors without that dependency in the POM, so for the moment i will include it in the PR.

**Comment by gulyx** [comment]
see my comment : https://github.com/LearnPAd/learnpad/pull/348#issuecomment-201395551

**Comment by gulyx** [comment]
I probably understood how to solve this issue. I will add some contributions to #348  ... but maybe beginning of next week. Stay tuned.

**Comment by gulyx** [comment]
see my comment : https://github.com/LearnPAd/learnpad/pull/348#issuecomment-202897230

**Comment by gulyx** [comment]
PR https://github.com/LearnPAd/learnpad/pull/363 should also contribute to this issue by changing the way CP handle the usedIDs dealing with Recommendations (e.g. notifying them to the CW).

As side remark i noticed that the RecommendationPanel of CW-UI does not show anything if there are no similar cases to report (i.e. no experts, no learning material). But this behaviour is not as expected.

**Comment by gulyx** [comment]
@tomjorquera note that from my tests the events procuded by the sim and then propagated by the mon do not include the whole set of data thst should be passed to the OR. To me olny case-id and sim-session-id are paased. Could please check and keep @semmeneg and me informed?

**Comment by gulyx** [comment]
... however, considering the history of this issue, i would say that likely it is a case of regression.

**Comment by gulyx** [comment]
It is worth to mention that i am testing with these settings : https://github.com/gulyx/learnpad/blob/sim-FixOnCasesDataForTheDemo/lp-simulation-environment/simulator/src/main/resources/static/Process.js

**Comment by tomjorquera** [comment]
Yep it was a regression caused by the change of ID in the Y2 demo model.
PR #370 fixes this.

**Comment by gulyx** [comment]
mmm unfortunately i cannot confirm yet!

**Comment by gulyx** [comment]
ok the latest commits (https://github.com/LearnPAd/learnpad/pull/370/commits/278e515a5366739f6bc93fece08516d4731f16e0 and https://github.com/LearnPAd/learnpad/pull/370/commits/a509cb05abfbce98ed3ffe240477949f1edc4a5a ) on PR https://github.com/LearnPAd/learnpad/pull/370 should have fixed the regression

**Comment by gulyx** [comment]
this should also help : PR https://github.com/LearnPAd/learnpad/pull/376
