### ISSUE TITLE
[cw] JS Comment Analysis

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#515]
@cjdelisle I merged your PR #499, but it seems that that implementation is not working fine with my browsers (i.e. chromium and firefox). 
In fact the popup with the suggestion are not displayed at all (when the string Sally Shugar is in the body of the comment) and also the comment section appears corrupted. Please see the screenshot
![screen1](https://cloud.githubusercontent.com/assets/8114713/17271187/9739d532-5675-11e6-9595-6d2476cd3d18.jpg)

Note that with commit https://github.com/LearnPAd/learnpad/pull/514/commits/cf714ab01936a2637af312a557bd645246dec503 I changed a bit your original implementation since the CP is the architectural element which is responsible to match/convert IDs among the different components.

**Comment by cjdelisle** [comment]
Well it's pretty clear that it's not working because the REST call is returning nothing. You can see this by doing the following request: ```curl -v -X POST -d '<p>this is a test</p>' 'http://localhost:8080/xwiki/rest/learnpad/cw/corefacade/semantic/Main/analysetext?userid=XWiki.Admin&title=&contextArtifactId='```
Perhaps it is that you have created an override method which is ceasing the call to analyseText away from the actual call location. For example the following:
https://github.com/LearnPAd/learnpad/blob/master/lp-core-platform/lp-cp-xwiki-implementation/src/main/java/eu/learnpad/core/impl/or/XwikiBridgeInterfaceRestResource.java#L272

**Comment by gulyx** [comment]
@cjdelisle I do not know why you used this URL in your test
> http://localhost:8080/xwiki/rest/learnpad/cw/corefacade/semantic/Main/analysetext

however your comment spotted to me a missing implementation of a method ... and some bug fix.
PR #516 should have solved this issue.

Thanks.
